CREATE TABLE passing_stats (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      team_abbr VARCHAR(10) REFERENCES teams(abbr),
      season INT NOT NULL,
      season_type VARCHAR(10) NOT NULL DEFAULT 'REG',
      games INT,
      completions INT,
      attempts INT,
      passing_yards INT,
      passing_tds INT,
      interceptions INT,
      sacks INT,
      sack_yards_lost INT,
      completion_pct DECIMAL(5,2),
      yards_per_attempt DECIMAL(5,2),
      adj_yards_per_attempt DECIMAL(5,2),
      net_yards_per_attempt DECIMAL(5,2),
      td_pct DECIMAL(5,2),
      int_pct DECIMAL(5,2),
      passer_rating DECIMAL(6,2),
      qbr DECIMAL(5,2),
      cpoe DECIMAL(6,2),
      epa_per_dropback DECIMAL(6,3),
      success_rate DECIMAL(5,2),
      pressure_rate DECIMAL(5,2),
      time_to_throw_avg DECIMAL(4,2),
      adot DECIMAL(5,2),
      on_target_pct DECIMAL(5,2),
      bad_throw_pct DECIMAL(5,2),
      blitzed_pct DECIMAL(5,2),
      scrambles INT,
      scramble_yards INT,
      scramble_tds INT,
      UNIQUE(player_id, season, season_type)
  );

  CREATE TABLE rushing_stats (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      team_abbr VARCHAR(10) REFERENCES teams(abbr),
      season INT NOT NULL,
      season_type VARCHAR(10) NOT NULL DEFAULT 'REG',
      games INT,
      carries INT,
      rushing_yards INT,
      rushing_tds INT,
      fumbles INT,
      fumbles_lost INT,
      rushing_first_downs INT,
      yards_per_carry DECIMAL(5,2),
      success_rate DECIMAL(5,2),
      rushing_epa DECIMAL(8,3),
      yards_after_contact DECIMAL(8,2),
      broken_tackles INT,
      yac_per_carry DECIMAL(5,2),
      stuff_rate DECIMAL(5,2),
      runs_10_plus INT,
      runs_20_plus INT,
      targets INT,
      receptions INT,
      receiving_yards INT,
      receiving_tds INT,
      yards_per_reception DECIMAL(5,2),
      UNIQUE(player_id, season, season_type)
  );

  CREATE TABLE receiving_stats (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      team_abbr VARCHAR(10) REFERENCES teams(abbr),
      season INT NOT NULL,
      season_type VARCHAR(10) NOT NULL DEFAULT 'REG',
      games INT,
      targets INT,
      receptions INT,
      receiving_yards INT,
      receiving_tds INT,
      drops INT,
      fumbles INT,
      catch_rate DECIMAL(5,2),
      yards_per_target DECIMAL(5,2),
      yards_per_reception DECIMAL(5,2),
      drop_rate DECIMAL(5,2),
      adot DECIMAL(5,2),
      air_yards INT,
      yards_after_catch DECIMAL(8,2),
      yac_per_reception DECIMAL(5,2),
      target_share DECIMAL(5,2),
      air_yards_share DECIMAL(5,2),
      wopr DECIMAL(5,3),
      epa_per_target DECIMAL(6,3),
      separation_avg DECIMAL(4,2),
      contested_catch_rate DECIMAL(5,2),
      red_zone_targets INT,
      end_zone_targets INT,
      UNIQUE(player_id, season, season_type)
  );

  CREATE INDEX idx_passing_stats_player_id ON passing_stats(player_id);
  CREATE INDEX idx_passing_stats_season ON passing_stats(season);
  CREATE INDEX idx_rushing_stats_player_id ON rushing_stats(player_id);
  CREATE INDEX idx_rushing_stats_season ON rushing_stats(season);
  CREATE INDEX idx_receiving_stats_player_id ON receiving_stats(player_id);
  CREATE INDEX idx_receiving_stats_season ON receiving_stats(season);

